server:
  port: 8080
spring:
    datasource:
      url: jdbc:postgresql://localhost:5432/postgres
      username: postgres
      password: 25293
    jpa:
      properties:
        hibernate:
          dialect: org.hibernate.dialect.PostgreSQL92Dialect
      hibernate:
        ddl-auto: update
upload:
  server:
    folder: C:\Users\azimjon\Documents\Nmadur\

api:
  placeholder: https://jsonplaceholder.typicode.com

jwt:
  token:
    secret: yes
    validity: 86400000



